### ISSUE TITLE
problema con el contains() de iterables

### ISSUE THREAD

**Issue by ClaraAllende** [ClaraAllende/nadieQuiereMiRepoTADP#14]
contains() no nos sirve en cuanto a que no usa el equals redefinido, tengo que investigar si usa el equals default y si puedo hacer que use nuestro equals...

**Comment by ClaraAllende** [comment]
Este es el código del contains() de Iterables:

public static boolean contains(Iterable<?> iterable, @Nullable Object element)
     {
       if (iterable instanceof Collection) {
          Collection<?> collection = (Collection<?>) iterable;
              try {
                return collection.contains(element);
              } catch (NullPointerException e) {
                return false;
                } catch (ClassCastException e) {
                 return false;
             }
       }
 return Iterators.contains(iterable.iterator(), element);
 }

Llama al contains de Collection, que en la documentación dice así:

contains

public boolean contains(Object o)
Returns true if this collection contains the specified element. More formally, returns true if and only if this collection contains at least one element e such that (o==null ? e==null : o.equals(e)).

o sea, usa el equals de Object. 

Y además, usa el contains de Iterators, que dice así:

```
public static boolean contains(Iterator<?> iterator, @Nullable Object element)
```

202      {
203        if (element == null) {
204          while (iterator.hasNext()) {
205            if (iterator.next() == null) {
206              return true;
207            }
208          }
209        } else {
210          while (iterator.hasNext()) {
211            if (element.equals(iterator.next())) {
212              return true;
213            }
214          }
215        }
216        return false;
217      }

que como hace element.equals, y element es de tipo Object, usa el de Object.

Ergo, hay que castear, o hacer algo para decirle explícitamente que queremos que use el redefinido, y no el de object xD

**Comment by jvillarejo** [comment]
Y este issue?

**Comment by jvillarejo** [comment]
Mostra es polimorfico, si redefinis el equals usa el de tu clase... 

Y si no pregunta por la instancia misma.

Donde está el problema?

**Comment by ClaraAllende** [comment]
Si, debería, pero no lo hace, y ese es el bug que hay que arreglar

2012/5/30 Juan Ignacio <
reply@reply.github.com

> Mostra es polimorfico, si redefinis el equals usa el de tu clase...
> 
> Y si no pregunta por la instancia misma.
> 
> Donde está el problema?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ClaraAllende/nadieQuiereMiRepoTADP/issues/14#issuecomment-6019554

## 

"_Most good programmers do programming not because they expect to get paid
or get adulation by the public, but because it is fun to program._"

Linus Torvalds
