### ISSUE TITLE
definir criterios

### ISSUE THREAD

**Issue by ClaraAllende** [ClaraAllende/nadieQuiereMiRepoTADP#2]
Eso, yo me hago cargo de programar los criterios.

Cosas a definir:
-si voy a tener una clase y dos subclases, como en Smalltalk
.relacionado con lo primero, sin los symbols como que mucho sentido no tiene, me voy a tener que fumar las combinaciones de mensajes xD
-son válidos solo para las personas, o pueden ser extensibles a los otros recursos?

**Comment by sancuba** [comment]
Cuando hablamos de criteros, nos referimos a los requisitos?
Es lindo el polimorfismo, pero me parece que no tiene sentido que los criterios de las personas apliquen a los recursos:
- RequisitoDeRecurso sabe tratar recursos
- RequisitoDePersona sabe tratar personas

Por otro lado se me ocurre algo: requisitos podrian manejar cantidad? Ejemplo: quiero 2 proyectores, quiero 3 diseñadores. Que les parece? Es mucho mas dificil implementar?

**Comment by ClaraAllende** [comment]
eeeh se pueden parametrizar... me gustaria polimorfismo
lo de las cantidades es viable si tengo algo onda take. Que dice el enunciado al respecto? SI es necesario, lo puedo implementar, pero si no, la verdad no le daría mucha pelota

**Comment by ClaraAllende** [comment]
Decisiones que charlamos con Lucas:
- Si tengo un método como filtrar(Recurso unRecurso), claramente quiero que sean polimórficos. (Persona hereda de recurso, así que bleh).
  -la otra opción es sobrecargar. Tengo que explorar cual me conviene más en este caso.
- No necesito una interface, voy a tener una clase criterio (le voy a cambiar el nombre xD) y de ahí puedo elegir hacer un double dispatch o un command. Voy a leer esos patrones a ver si me quedo con alguno, o con nigumo xD
